# Generated by Django 5.2.3 on 2025-07-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='channel_fit',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='demand_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='forecasted_sales',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='image_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='item_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='logistics_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='manual_review_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='recommended_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_returns', to='returns.store'),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='resale_probability_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='current_inventory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='forecasted_sales',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
