# Generated by Django 5.2.3 on 2025-07-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_product_item_value_returnrequest_channel_fit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='auto_action_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='auto_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='exchange_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='manual_review_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
