# Generated by Django 5.2.3 on 2025-07-05 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_returnrequest_auto_action_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('store_location', models.CharField(max_length=255)),
                ('demand', models.FloatField()),
                ('product_price', models.FloatField()),
                ('cost_price', models.FloatField()),
                ('logistics_cost_per_unit', models.FloatField()),
                ('profit_margin', models.FloatField()),
                ('profit_margin_pct', models.FloatField()),
            ],
            options={
                'unique_together': {('product_id', 'store_location')},
            },
        ),
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_product_id', models.IntegerField()),
                ('csv_product_name', models.CharField(max_length=255)),
                ('app_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='returns.product')),
            ],
        ),
        migrations.CreateModel(
            name='StoreMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_store_location', models.CharField(max_length=255)),
                ('app_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='returns.store')),
            ],
        ),
    ]
